/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin.perfil'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminFuncionariosRouteImport } from './routes/_authenticated/admin.funcionarios'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminAtendimentosRouteImport } from './routes/_authenticated/admin.atendimentos'
import { Route as AuthenticatedAdminConfiguracoesOperacaoRouteImport } from './routes/_authenticated/admin.configuracoes_.operacao'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFuncionariosRoute =
  AuthenticatedAdminFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtendimentosRoute =
  AuthenticatedAdminAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesOperacaoRoute =
  AuthenticatedAdminConfiguracoesOperacaoRouteImport.update({
    id: '/configuracoes_/operacao',
    path: '/configuracoes/operacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/atendimentos': typeof AuthenticatedAdminAtendimentosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/configuracoes/operacao': typeof AuthenticatedAdminConfiguracoesOperacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/atendimentos': typeof AuthenticatedAdminAtendimentosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/configuracoes/operacao': typeof AuthenticatedAdminConfiguracoesOperacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/atendimentos': typeof AuthenticatedAdminAtendimentosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/configuracoes_/operacao': typeof AuthenticatedAdminConfiguracoesOperacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/admin/atendimentos'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/funcionarios'
    | '/admin/notificacoes'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin/'
    | '/admin/configuracoes/operacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/atendimentos'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/funcionarios'
    | '/admin/notificacoes'
    | '/admin/pedidos'
    | '/admin/perfil'
    | '/admin'
    | '/admin/configuracoes/operacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/admin/atendimentos'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/funcionarios'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/configuracoes_/operacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funcionarios': {
      id: '/_authenticated/admin/funcionarios'
      path: '/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AuthenticatedAdminFuncionariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/atendimentos': {
      id: '/_authenticated/admin/atendimentos'
      path: '/atendimentos'
      fullPath: '/admin/atendimentos'
      preLoaderRoute: typeof AuthenticatedAdminAtendimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes_/operacao': {
      id: '/_authenticated/admin/configuracoes_/operacao'
      path: '/configuracoes/operacao'
      fullPath: '/admin/configuracoes/operacao'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesOperacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAtendimentosRoute: typeof AuthenticatedAdminAtendimentosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminFuncionariosRoute: typeof AuthenticatedAdminFuncionariosRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminConfiguracoesOperacaoRoute: typeof AuthenticatedAdminConfiguracoesOperacaoRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAtendimentosRoute: AuthenticatedAdminAtendimentosRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminFuncionariosRoute: AuthenticatedAdminFuncionariosRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminConfiguracoesOperacaoRoute:
    AuthenticatedAdminConfiguracoesOperacaoRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
