DELETE FROM public.pedido_transicoes;

INSERT INTO public.pedido_transicoes (de, para) VALUES
  ('novo','whatsapp_declarado'),
  ('novo','aguardando_atendimento'),
  ('novo','em_atendimento'),
  ('novo','cancelado'),
  ('whatsapp_declarado','aguardando_atendimento'),
  ('whatsapp_declarado','em_atendimento'),
  ('whatsapp_declarado','cancelado'),
  ('aguardando_atendimento','em_atendimento'),
  ('aguardando_atendimento','cancelado'),
  ('em_atendimento','aguardando_atendimento'),
  ('em_atendimento','aguardando_pagamento'),
  ('em_atendimento','cancelado'),
  ('aguardando_pagamento','pagamento_confirmado'),
  ('aguardando_pagamento','cancelado'),
  ('pagamento_confirmado','separado'),
  ('pagamento_confirmado','cancelado'),
  ('separado','reservado'),
  ('separado','aguardando_retirada'),
  ('separado','enviado'),
  ('separado','cancelado'),
  ('reservado','aguardando_retirada'),
  ('reservado','enviado'),
  ('reservado','cancelado'),
  ('aguardando_retirada','finalizado'),
  ('aguardando_retirada','cancelado'),
  ('enviado','finalizado'),
  ('enviado','cancelado'),
  ('finalizado','devolvido');